### ISSUE TITLE
lbaas-pool-delete fails in liberty

### ISSUE THREAD

**Issue by Cedev** [a10networks/a10-neutron-lbaas#131]
Using the stable/liberty branch, with an existing pool 

```
$ neutron lbaas-pool-list
+--------------------------------------+-------+----------+----------------+
| id                                   | name  | protocol | admin_state_up |
+--------------------------------------+-------+----------+----------------+
| 05eaabd4-c3cc-4747-bb40-6212b92d8757 | pool1 | TCP      | True           |
+--------------------------------------+-------+----------+----------------+
```

Deleting the pool fails

```
$ neutron lbaas-pool-delete pool1
An error happened in the driver
```

The following is logged

```
2015-11-13 18:00:53.029 ERROR neutron_lbaas.services.loadbalancer.plugin [req-70aa3bcb-7500-4657-a496-71ba6d697ea0 admin 2d205c4f252249acaa8c1bc53b40f1dd]
 There was an error in the driver
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin Traceback (most recent call last):
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/services/loadbalancer/plugin.py", line 471, in _call_driver_operation
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     driver_method(context, db_entity)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/drivers/a10networks/driver_v2.py", line 80, in delete
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     self.driver.a10.pool.delete(context, pool)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/home/ubuntu/a10-neutron-lbaas/a10_neutron_lbaas/v2/handler_pool.py", line 72, in delete
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     self.a10_driver.hm._delete(c, context, pool.healthmonitor)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/home/ubuntu/a10-neutron-lbaas/a10_neutron_lbaas/v2/handler_hm.py", line 96, in _delete
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     pool_name = self._pool_name(context, pool=hm.pool)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/home/ubuntu/a10-neutron-lbaas/a10_neutron_lbaas/handler_base.py", line 39, in _pool_name
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     pool = self.neutron.pool_get(context, pool_id)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/home/ubuntu/a10-neutron-lbaas/a10_neutron_lbaas/v2/neutron_ops.py", line 47, in pool_get
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     return self.plugin.db.get_pool(context, pool_id)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/db/loadbalancer/loadbalancer_dbv2.py", line 481, in get_pool
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     pool_db = self._get_resource(context, models.PoolV2, id)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/db/loadbalancer/loadbalancer_dbv2.py", line 70, in _get_resource
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin     raise loadbalancerv2.EntityNotFound(name=model.NAME, id=id)
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin EntityNotFound: pool None could not be found
2015-11-13 18:00:53.029 TRACE neutron_lbaas.services.loadbalancer.plugin
```

**Comment by Cedev** [comment]
The pool still had a healthmonitor. Deleting the healthmonitor first worked.

**Comment by mdurrant-b3** [comment]
Associated w/ #94

**Comment by Cedev** [comment]
This is fixed in master (1.4 series, PR #144). There's a backport PR #154 to merge it into a 1.3 series driver.
