### ISSUE TITLE
Orchestration - StopIteration error if no "a10"-tagged images exist

### ISSUE THREAD

**Issue by mdurrant-b3** [a10networks/a10-neutron-lbaas#198]
```
2016-01-29 22:52:37.014 ERROR neutron_lbaas.services.loadbalancer.plugin [req-40fb6abf-5d0a-453c-b0f5-b9a7e01e7f87 admin c3898b802ed446089143456dbfeede
38] There was an error in the driver
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin Traceback (most recent call last):
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/services/loadbalancer/plugin.py
", line 483, in _call_driver_operation
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     driver_method(context, db_entity)
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/opt/stack/neutron-lbaas/neutron_lbaas/drivers/a10networks/driver_v2.p
y", line 44, in create
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     self.driver.a10.lb.create(context, lb)
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/src/a10-neutron-lbaas/a10_neutron_lbaas/v2/handler_lb.py", line 73, in create
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     with a10.A10WriteStatusContext(self, context, lb) as c:
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/src/a10-neutron-lbaas/a10_neutron_lbaas/a10_context.py", line 43, in __enter__
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     appliance = self.inventory.find(self.openstack_lbaas_obj)
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/src/a10-neutron-lbaas/a10_neutron_lbaas/v2/inventory.py", line 26, in find
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     appliance = self.select_appliance(openstack_lbaas_obj)
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/src/a10-neutron-lbaas/a10_neutron_lbaas/inventory.py", line 64, in select_appliance
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     selected_devices = scheduling_hooks.select_devices(self.a10_context, device_configs)
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/src/a10-neutron-lbaas/a10_neutron_lbaas/scheduling_hooks.py", line 50, in select_devices
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin     device = next(devices.__iter__())
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin StopIteration
2016-01-29 22:52:37.014 TRACE neutron_lbaas.services.loadbalancer.plugin 
```

**Comment by Cedev** [comment]
We need to catch this and throw a nice exception saying that no devices are available.

We need to do the same thing in the migration when you run the migration with an existing loadbalancer and vip but with no existing devices. (#172)

**Comment by mdurrant-b3** [comment]
Based on PR #199 - might end up folding these all in to one commit if this PR gets opened before 199 gets merged and closed.

**Comment by mdurrant-b3** [comment]
Closing as #200 has been merged.
