### ISSUE TITLE
community tempest tests failing against ACOS 4.0.3-GA with template errors

### ISSUE THREAD

**Issue by dougwig** [a10networks/a10-neutron-lbaas#266]
send: 'POST /axapi/v3/slb/virtual-server/8f720869-8a0f-456f-bce7-ef8b23c390a2/port/ HTTP/1.1\r\nHost: 10.48.51.195\r\nContent-Length: 260\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: ACOS-Client-AGENT-1.3.0alpha\r\nConnection: keep-alive\r\nContent-type: application/json\r\nAuthorization: A10 c23bc606ad4b3b17c0b62b1cec8e26\r\n\r\n{"port": {"service-group": "6277216b-16fa-439f-b435-bfd29507006a", "protocol": "tcp", "name": "8f720869-8a0f-456f-bce7-ef8b23c390a2_VPORT", "auto": 0, "template-persist-source-ip": null, "extended-stats": 0, "port-number": 81, "template-persist-cookie": null}}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Date: Thu, 24 Mar 2016 22:41:03 GMT
header: Server: Apache
header: Content-Length: 200
header: Connection: close
header: Content-Type: application/json
axapi_http: data = {
    "response": {
        "status": "fail",
        "err": {
            "msg": "JSON message is wrong.",
            "code": 1023508480,
            "from": "JSON",
            "location": "port.template-persist-cookie"
        }
    }
}
2016-03-24 22:41:03.367 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: data = {
    "response": {
        "status": "fail",
        "err": {
            "msg": "JSON message is wrong.",
            "code": 1023508480,
            "from": "JSON",
            "location": "port.template-persist-cookie"
        }
    }
} request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:123
axapi_http: full url = https://10.48.51.195:443/axapi/v3/logoff
2016-03-24 22:41:03.393 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: full url = https://10.48.51.195:443/axapi/v3/logoff request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:67
axapi_http: POST url = /axapi/v3/logoff
2016-03-24 22:41:03.393 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: POST url = /axapi/v3/logoff request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:68
axapi_http: params = {}
2016-03-24 22:41:03.394 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: params = {} request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:69
axapi_http: headers = {
    "Content-type": "application/json",
    "Authorization": "A10 c23bc606ad4b3b17c0b62b1cec8e26",
    "User-Agent": "ACOS-Client-AGENT-1.3.0alpha"
}
2016-03-24 22:41:03.394 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: headers = {
    "Content-type": "application/json",
    "Authorization": "A10 c23bc606ad4b3b17c0b62b1cec8e26",
    "User-Agent": "ACOS-Client-AGENT-1.3.0alpha"
} request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:95
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
send: 'POST /axapi/v3/logoff HTTP/1.1\r\nHost: 10.48.51.195\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: ACOS-Client-AGENT-1.3.0alpha\r\nConnection: keep-alive\r\nContent-type: application/json\r\nAuthorization: A10 c23bc606ad4b3b17c0b62b1cec8e26\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 24 Mar 2016 22:41:03 GMT
header: Server: Apache
header: Content-Length: 42
header: Connection: close
header: Content-Type: application/json
axapi_http: data = {
    "response": {
        "status": "OK"
    }
}
2016-03-24 22:41:03.409 4850 DEBUG acos_client.v30.axapi_http [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] axapi_http: data = {
    "response": {
        "status": "OK"
    }
} request /usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py:123
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource [req-6fae26a4-6d11-4265-9a93-e235ad8d7e40 tempest-BaseTestCase-297693841 -] create failed
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource Traceback (most recent call last):
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron/neutron/api/v2/resource.py", line 84, in resource
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron/neutron/api/v2/base.py", line 410, in create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     return self._create(request, body, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 148, in wrapper
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     self.force_reraise()
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 138, in wrapper
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron/neutron/api/v2/base.py", line 521, in _create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     obj = do_create(body)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron/neutron/api/v2/base.py", line 503, in do_create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     request.context, reservation.reservation_id)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     self.force_reraise()
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron/neutron/api/v2/base.py", line 496, in do_create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     return obj_creator(request.context, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron-lbaas/neutron_lbaas/services/loadbalancer/plugin.py", line 149, in create_vip
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     driver.create_vip(context, v)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/opt/stack/new/neutron-lbaas/neutron_lbaas/services/loadbalancer/drivers/a10networks/driver_v1.py", line 140, in create_vip
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     self.a10.vip.create(context, vip)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/a10_neutron_lbaas/v1/handler_vip.py", line 98, in create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     axapi_args=vport_args)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/slb/virtual_port.py", line 88, in create
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     s_pers_name, c_pers_name, status, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/slb/virtual_port.py", line 81, in _set
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     return self._post(url, params, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/base.py", line 38, in _post
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     return self._request('POST', action, params, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/base.py", line 32, in _request
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     self.auth_header, **kwargs)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/axapi_http.py", line 127, in request
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     acos_responses.raise_axapi_ex(r, method, api_url)
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/acos_client/v30/responses.py", line 193, in raise_axapi_ex
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource     raise ae.ACOSException(code, response['response']['err']['msg'])
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource ACOSException: 1023508480 JSON message is wrong.
2016-03-24 22:41:03.440 4850 ERROR neutron.api.v2.resource

**Comment by mdurrant-b3** [comment]
Confirmed defect on 4.0.3, defect not present in 4.0.1.  I don't think we can start introducing version-specific code into our handlers or acos-client.  Creative projections of the data to make it compatible with both appears to be in our future. :crystal_ball:

**Comment by dougwig** [comment]
It only occurs in 4.0.3, so I'd do

try:
   code that works everywhere but 4.0.3
except <specific exception>
   # workaround backwards-combat regression in 4.0.3-GA with ...
   code that works in 4.0.3

that's the model we've used elsewhere

**Comment by dougwig** [comment]
This looks to be fixed by https://github.com/a10networks/acos-client/pull/105 ; we'll need a a-c pypi version bump to close this issue.
