### ISSUE TITLE
[openstack-rocky] 404 Client Error: Not Found for url: http://192.168.1.1:8181/simple/a10-openstack-lib/

### ISSUE THREAD

**Issue by hoangphuc2019** [a10networks/a10-neutron-lbaas#460]
# pip install git+https://github.com/a10networks/a10-neutron-lbaas.git
Collecting git+https://github.com/a10networks/a10-neutron-lbaas.git
  Cloning https://github.com/a10networks/a10-neutron-lbaas.git to /tmp/pip-iVk0VT-build
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 397, in _check_skip_installed
    finder.find_requirement(req_to_install, self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 760, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://192.168.1.1:8181/simple/a10-openstack-lib/

**Comment by mdurrant-b3** [comment]
Please check your proxy/pypi configuration. 

Closing this issue as there isn't enough data to reproduce or even file.
